server:
  context-path: /spring-cloud-config-server
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akkaldevi/spring-boot-demos/tree/master/spring-cloud-config-repo/
